libraries = -lXt -lX11 -lGL -lGLU
LIBRARIES = -L/usr/lib/mesa -L/home/hutch/accis/ -laccisX -lXt -lX11 
# Things just needed for the test routine:
UTILITIES=usleepf.o
#COMPILE-SWITCHES = -Wall -O2  -I. 
COMPILE-SWITCHES = -Wall  -I. -g  -ffortran-bounds-check
#################################################################
# Decide which compiler to use.
ifeq ("$(G77)","")
# I don't know why this has to be overridden. 
# But within this section of code G77 is not set without an override.
	override G77=$(shell cat compiler 2>/dev/null)
	ifeq ("$(G77)","")
# Default compiler. Ought to be used if a strange make target is used 
# on the very first call.
# After that, compiler ought to be set on disk and used.
		override G77=gfortran
	endif
endif
# In g77 -Wno-globals silences spurious type messages on reduce.f
# This is unrecognized by gfortan. For which no-unused is better.
NGW=-Wno-unused
ifeq ("$(G77)","g77")	
  NGW=-Wno-globals
endif
# export this so it is inherited by sub-makes.
export G77
##################################################################

% :: %.f makefile $(OBJECTS) $(UTILITIES)
	$(G77)  -o $* $(COMPILE-SWITCHES) $*.f $(OBJECTS) $(UTILITIES) $(LIBRARIES)

%.o :: %.f makefile $(HEADERS)
	$(G77)  -c $(COMPILE-SWITCHES) $*.f


lorentztrack : lorentztrack.f accis/libaccisX.a
	$(G77) -o lorentztrack -fno-backslash lorentztrack.f -laccisX $(LIBRARIES) $(libraries)

highb : highb.f
	$(G77)  -o highb $(COMPILE-SWITCHES) highb.f $(OBJECTS) $(LIBRARIES)

accis/libaccisX.a : accis/*.f accis/*.c accis/*.h
	make -C accis

clean :
	rm -f *.o plot*.ps
